name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# Jest Test CI
  JestTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Check if Node.js is installed
      run: node --version || echo 'Node.js is not installed'
      id: check_node_installed
      continue-on-error: true
    
    - name: Install Node.js and npm
      if: steps.check_node_installed.outcome == 'failure'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      
    - name: Install dependencies in server directory
      run: npm install
      working-directory: server/

    - name: Check if mongod is running
      run: ps aux | grep -v grep | grep mongod || echo 'mongod is not running'
      id: check_mongod_running
      continue-on-error: true

    - name: Run mongod if not running
      if: steps.check_mongod_running.outcome == 'failure'
      run: mongod --config /opt/homebrew/etc/mongod.conf --fork

    - name: Set DB_URL variable
      run: echo "DB_URL=mongodb://127.0.0.1:27017/fake_so" >> $GITHUB_ENV

    - name: Run destroy.js
      env:
        DB_URL: ${{ env.DB_URL }}
      run: node destroy.js $DB_URL
      working-directory: server/

    - name: Run init.js
      env:
        DB_URL: ${{ env.DB_URL }}
      run: node init.js $DB_URL
      working-directory: server/

    - name: Run Jest Test
      run: npm test
      working-directory: server/
      env: 
        CI: true
        
# Cypress Test CI

  CypressTest:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if Node.js is installed
      run: node --version || echo 'Node.js is not installed'
      id: check_node_installed
      continue-on-error: true

    - name: Install Node.js and npm
      if: steps.check_node_installed.outcome == 'failure'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      
    - name: Install dependencies in server directory
      run: npm install
      working-directory: server/

    - name: Check if mongod is running
      run: ps aux | grep -v grep | grep mongod || echo 'mongod is not running'
      id: check_mongod_running
      continue-on-error: true

    - name: Run mongod if not running
      if: steps.check_mongod_running.outcome == 'failure'
      run: mongod --config /opt/homebrew/etc/mongod.conf --fork

    - name: Set DB_URL variable
      run: echo "DB_URL=mongodb://127.0.0.1:27017/fake_so" >> $GITHUB_ENV

    - name: Run destroy.js
      env:
        DB_URL: ${{ env.DB_URL }}
      run: node destroy.js $DB_URL
      working-directory: server/

    - name: Run init.js
      env:
        DB_URL: ${{ env.DB_URL }}
      run: node init.js $DB_URL
      working-directory: server/

    - name: Start the node server
      run: node server.js > server.log 2>&1 &
      working-directory: server/ 

    - name: Install dependencies in client directory
      run: npm install 
      working-directory: client/

    - name: Start the Client
      run: npm start &
      working-directory: client/

    - name: Install testing dependencies
      run: npm install cypress
      working-directory: client/

    - name: Run e2e tests
      run: npx cypress run --spec cypress/e2e/
      working-directory: client/

    - name: Kill the node server process
      run: kill $(lsof -t -i:8000) || true

    - name: Stop the client process
      run: kill $(lsof -t -i:3000) || true
